menu:
- {name: 'about', url: '/about/'}
#- {name: 'research', url: '/research/'}
#- {name: 'teaching', url: '/teaching/'}
#- {name: 'supervision', url: '/supervision/'}
- {name: 'engagement', url: '/engagement/'}
- {name: 'publications', url: '/publications/'}
- {name: 'cv', url: '/cv/'}
- {name: 'Contact', url: '#contact'}

social:
#- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kurtmarais/'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0002-8820-044X'}
- {icon: 'google', link: 'https://scholar.google.com/citations?hl=en&user=V0FVb_UAAAAJ'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Kurt-Marais'}
#- {icon: 'interactive-archive', link: 'https://researcherprofiles.sun.ac.za/17019-kurt-marais'}
