menu:
- {name: 'about', url: '/about/'}
- {name: 'research', url: '/research/'}
- {name: 'teaching', url: '/teaching/'}
#- {name: 'supervision', url: '/supervision/'}
#- {name: 'speaking', url: '/speaking/'}
- {name: 'publications', url: '/publications/'}
#- {name: 'cv', url: '/cv/'}

social:
#- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kurtmarais/'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0002-8820-044X'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Kurt-Marais'}
- {icon: 'x-twitter', link: 'https://x.com/maraisk_'}
- {icon: 'user-graduate', link: 'https://researcherprofiles.sun.ac.za/17019-kurt-marais'}
