menu:
- {name: 'about', url: '/about/'}
- {name: 'research', url: '/research/'}
- {name: 'teaching', url: '/teaching/'}
- {name: 'supervision', url: '/supervision/'}
- {name: 'speaking', url: '/speaking/'}
- {name: 'publications', url: '/publications/'}
- {name: 'cv', url: '/cv/'}

social:
- {icon: 'github', link: '#'}
- {icon: 'linkedin', url: "https://www.linkedin.com/in/kurtmarais/"}
- {icon: 'orcid', url: "https://orcid.org/0000-0002-8820-044X"}
